# Official docker image.
image: docker:latest

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - cd GymAPI/GymAPI.Web
  - docker login -u "$CI_REGISTRY_USER" -p "$HEROKU_API_KEY" $CI_REGISTRY
  - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-npm
  - npm i -g heroku

build:
  stage: build
  script:
    - docker run -t -v $PWD:/app/GymAPI.Web --workdir /app microsoft/dotnet:2.1-sdk bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"

test:
  stage: test
  script:
    - docker run -t -v $PWD:/app/Tests --workdir /app microsoft/dotnet:2.1-sdk bash -c "dotnet test"
    #- dotnet test

deploy:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/gym-lds/web .
    - docker push $CI_REGISTRY/gym-lds/web
    - heroku container:release web --app gym-lds
  only:
    - master
