stages:
  - build
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

build:
  image: docker:latest
  stage: build
  environment:
    name: staging
  script:
    - cd GymAPI/GymAPI.Web
    - docker run -t -v $PWD:/app --workdir /app microsoft/dotnet:2.1-sdk bash -c "dotnet restore && dotnet publish -c Release -o ./bin/Release/PublishOutput"
  tags:
    - local-runner

test:
  image: microsoft/dotnet:2.1-sdk
  stage: test
  environment:
    name: staging
  script:
    - cd GymAPI/Tests
    - dotnet test
  tags:
    - local-runner  

deploy:
  image: docker:latest
  stage: deploy
  environment:
    name: staging
  script:
    - cd GymAPI/GymAPI.Web
    - docker login -u "$CI_REGISTRY_USER" -p "$HEROKU_API_KEY" $CI_REGISTRY
    - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-npm
    - npm i -g heroku
    - docker build -t $CI_REGISTRY/gym-lds/web .
    - docker push $CI_REGISTRY/gym-lds/web
    - heroku container:release web --app gym-lds
  only:
    - master
  tags:
    - local-runner
