stages:
  - build
  - test
  - deploy
  
build:
  stage: build
  script:
    - cd GymAPI && dotnet build

#test:
#  stage: test
#  script:
#    - dotnet test

#deploy:
#  stage: deploy
#  script:
#    - C:\Scripts\Publish.cmd
#  environment:
#    name: staging
#  only:
#    - master
