# Official docker image.
image: docker:latest

stages:
  - build
  - test
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
  - cd GymAPI
  - docker login -u "$CI_REGISTRY_USER" -p "$HEROKU_API_KEY" $CI_REGISTRY
  - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community nodejs-npm
  - npm i -g heroku

build:
  stage: build
  script:
    - docker build -t gym-lds ./

#test:
#  stage: test
#  script:
#    - dotnet test

deploy:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/gym-lds/web .
    - docker push $CI_REGISTRY/gym-lds/web
    - heroku container:release web --app gym-lds
  only:
    - master
