// <auto-generated />
using System;
using GymAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymAPI.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20181121230911_AddTrainingPlans")]
    partial class AddTrainingPlans
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497");

            modelBuilder.Entity("GymAPI.Models.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("FirstName");

                    b.Property<float>("HeightInMeters");

                    b.Property<string>("LastName");

                    b.Property<long>("Nif");

                    b.Property<int?>("TrainingPlanId");

                    b.Property<float>("WeightInKg");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GymAPI.Models.ClientCheckIn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("At");

                    b.Property<long?>("ClientId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientCheckIn");
                });

            modelBuilder.Entity("GymAPI.Models.ClientNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ClientId");

                    b.Property<bool>("IsUnread");

                    b.Property<string>("Message");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientNotification");
                });

            modelBuilder.Entity("GymAPI.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("DifficultyLevel");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.Property<int>("TargetMuscleGroup");

                    b.Property<int?>("TrainingPlanId");

                    b.Property<int?>("TrainingPlanId1");

                    b.Property<int?>("TrainingPlanId2");

                    b.Property<int?>("TrainingPlanId3");

                    b.Property<int?>("TrainingPlanId4");

                    b.Property<int?>("TrainingPlanId5");

                    b.Property<int?>("TrainingPlanId6");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.HasIndex("TrainingPlanId1");

                    b.HasIndex("TrainingPlanId2");

                    b.HasIndex("TrainingPlanId3");

                    b.HasIndex("TrainingPlanId4");

                    b.HasIndex("TrainingPlanId5");

                    b.HasIndex("TrainingPlanId6");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("GymAPI.Models.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("GymAPI.Models.Client", b =>
                {
                    b.HasOne("GymAPI.Models.TrainingPlan", "TrainingPlan")
                        .WithMany()
                        .HasForeignKey("TrainingPlanId");
                });

            modelBuilder.Entity("GymAPI.Models.ClientCheckIn", b =>
                {
                    b.HasOne("GymAPI.Models.Client")
                        .WithMany("CheckInHistory")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("GymAPI.Models.ClientNotification", b =>
                {
                    b.HasOne("GymAPI.Models.Client")
                        .WithMany("Notifications")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("GymAPI.Models.Exercise", b =>
                {
                    b.HasOne("GymAPI.Models.TrainingPlan")
                        .WithMany("FridayExercises")
                        .HasForeignKey("TrainingPlanId");

                    b.HasOne("GymAPI.Models.TrainingPlan")
                        .WithMany("MondayExercises")
                        .HasForeignKey("TrainingPlanId1");

                    b.HasOne("GymAPI.Models.TrainingPlan")
                        .WithMany("SaturdayExercises")
                        .HasForeignKey("TrainingPlanId2");

                    b.HasOne("GymAPI.Models.TrainingPlan")
                        .WithMany("SundayExercises")
                        .HasForeignKey("TrainingPlanId3");

                    b.HasOne("GymAPI.Models.TrainingPlan")
                        .WithMany("ThursdayExercises")
                        .HasForeignKey("TrainingPlanId4");

                    b.HasOne("GymAPI.Models.TrainingPlan")
                        .WithMany("TuesdayExercises")
                        .HasForeignKey("TrainingPlanId5");

                    b.HasOne("GymAPI.Models.TrainingPlan")
                        .WithMany("WednesdayExercises")
                        .HasForeignKey("TrainingPlanId6");
                });
#pragma warning restore 612, 618
        }
    }
}
